CREATE TABLE T20I (
    Team1	VARCHAR(50),
    Team2	VARCHAR(50),
    Winner	VARCHAR(50),
    Margin	VARCHAR(50),
    MatchDate	DATE,
    Ground	VARCHAR(50)
);


INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'West Indies', '5 wickets', 'Nov 16, 2024', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Pakistan', 'Australia', '13 runs', 'Nov 16, 2024', 'Sydney');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'India', 'India', '135 runs', 'Nov 15, 2024', 'Johannesburg');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'England', '3 wickets', 'Nov 14, 2024', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Pakistan', 'Australia', '29 runs', 'Nov 14, 2024', 'Brisbane');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'India', 'India', '11 runs', 'Nov 13, 2024', 'Centurion');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'England', '7 wickets', 'Nov 10, 2024', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'India', 'South Africa', '3 wickets', 'Nov 10, 2024', 'Gqeberha');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'New Zealand', 'New Zealand', '5 runs', 'Nov 10, 2024', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'England', '8 wickets', 'Nov 9, 2024', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'New Zealand', 'Sri Lanka', '4 wickets', 'Nov 9, 2024', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'India', 'India', '61 runs', 'Nov 8, 2024', 'Durban');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'West Indies', 'Sri Lanka', '9 wickets', 'Oct 17, 2024', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'West Indies', 'Sri Lanka', '73 runs', 'Oct 15, 2024', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'West Indies', 'West Indies', '5 wickets', 'Oct 13, 2024', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Bangladesh', 'India', '133 runs', 'Oct 12, 2024', 'Hyderabad');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Bangladesh', 'India', '86 runs', 'Oct 9, 2024', 'Delhi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Bangladesh', 'India', '7 wickets', 'Oct 6, 2024', 'Gwalior');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'Nepal', 'Canada', '4 wickets', 'Oct 1, 2024', 'King City (NW)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'South Africa', 'Ireland', '10 runs', 'Sep 29, 2024', 'Abu Dhabi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'Nepal', 'Canada', '14 runs', 'Sep 28, 2024', 'King City (NW)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'South Africa', 'South Africa', '8 wickets', 'Sep 27, 2024', 'Abu Dhabi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Australia', 'England', '3 wickets', 'Sep 13, 2024', 'Cardiff');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Australia', 'Australia', '28 runs', 'Sep 11, 2024', 'Southampton');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Scotland', 'Australia', 'Australia', '6 wickets', 'Sep 7, 2024', 'Edinburgh');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Scotland', 'Australia', 'Australia', '70 runs', 'Sep 6, 2024', 'Edinburgh');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Scotland', 'Australia', 'Australia', '7 wickets', 'Sep 4, 2024', 'Edinburgh');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '8 wickets', 'Aug 27, 2024', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'U.S.A.', 'U.S.A.', '20 runs', 'Aug 27, 2024', 'The Hague');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '30 runs', 'Aug 25, 2024', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '7 wickets', 'Aug 23, 2024', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'India', 'tied', '-', 'Jul 30, 2024', 'Pallekele');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'India', 'India', '7 wickets', 'Jul 28, 2024', 'Pallekele');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'India', 'India', '43 runs', 'Jul 27, 2024', 'Pallekele');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'India', '42 runs', 'Jul 14, 2024', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'India', '10 wickets', 'Jul 13, 2024', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'India', '23 runs', 'Jul 10, 2024', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'India', '100 runs', 'Jul 7, 2024', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Zimbabwe', 'India', 'Zimbabwe', '13 runs', 'Jul 6, 2024', 'Harare');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'South Africa', 'India', '7 runs', 'Jun 29, 2024', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'India', 'India', '68 runs', 'Jun 27, 2024', 'Providence');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'South Africa', 'South Africa', '9 wickets', 'Jun 26, 2024', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Bangladesh', 'Afghanistan', '8 runs', 'Jun 24, 2024', 'Kingstown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'India', 'India', '24 runs', 'Jun 24, 2024', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'South Africa', '3 wickets', 'Jun 23, 2024', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'U.S.A.', 'England', '10 wickets', 'Jun 23, 2024', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Australia', 'Afghanistan', '21 runs', 'Jun 22, 2024', 'Kingstown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'India', 'India', '50 runs', 'Jun 22, 2024', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'U.S.A.', 'West Indies', '9 wickets', 'Jun 21, 2024', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'South Africa', 'South Africa', '7 runs', 'Jun 21, 2024', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Bangladesh', 'Australia', '28 runs', 'Jun 20, 2024', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'India', 'India', '47 runs', 'Jun 20, 2024', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'England', 'England', '8 wickets', 'Jun 19, 2024', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'U.S.A.', 'South Africa', '18 runs', 'Jun 19, 2024', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'Afghanistan', 'West Indies', '104 runs', 'Jun 17, 2024', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Nepal', 'Bangladesh', '21 runs', 'Jun 16, 2024', 'Kingstown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'Pakistan', 'Pakistan', '3 wickets', 'Jun 16, 2024', 'Lauderhill');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Scotland', 'Australia', '5 wickets', 'Jun 15, 2024', 'Gros Islet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Namibia', 'England', '41 runs', 'Jun 15, 2024', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Nepal', 'South Africa', 'South Africa', '1 run', 'Jun 14, 2024', 'Kingstown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'New Zealand', 'West Indies', '13 runs', 'Jun 12, 2024', 'Tarouba');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'India', 'India', '7 wickets', 'Jun 12, 2024', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'Namibia', 'Australia', '9 wickets', 'Jun 11, 2024', 'North Sound');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'Pakistan', 'Pakistan', '7 wickets', 'Jun 11, 2024', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'South Africa', 'South Africa', '4 runs', 'Jun 10, 2024', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Pakistan', 'India', '6 runs', 'Jun 9, 2024', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'England', 'Australia', '36 runs', 'Jun 8, 2024', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Sri Lanka', 'Bangladesh', '2 wickets', 'Jun 7, 2024', 'Dallas');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'New Zealand', 'Afghanistan', '84 runs', 'Jun 7, 2024', 'Providence');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Canada', 'Ireland', 'Canada', '12 runs', 'Jun 7, 2024', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Pakistan', 'tied', '-', 'Jun 6, 2024', 'Dallas');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Ireland', 'India', '8 wickets', 'Jun 5, 2024', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Scotland', 'no result', '-', 'Jun 4, 2024', 'Bridgetown');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('South Africa', 'Sri Lanka', 'South Africa', '6 wickets', 'Jun 3, 2024', 'New York');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Canada', 'U.S.A.', '7 wickets', 'Jun 1, 2024', 'Dallas');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Pakistan', 'England', '7 wickets', 'May 30, 2024', 'The Oval');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '8 wickets', 'May 26, 2024', 'Kingston');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '16 runs', 'May 25, 2024', 'Kingston');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Bangladesh', 'Bangladesh', '10 wickets', 'May 25, 2024', 'Prairie View');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('England', 'Pakistan', 'England', '23 runs', 'May 25, 2024', 'Birmingham');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('West Indies', 'South Africa', 'West Indies', '28 runs', 'May 23, 2024', 'Kingston');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Bangladesh', 'U.S.A.', '6 runs', 'May 23, 2024', 'Prairie View');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('U.S.A.', 'Bangladesh', 'U.S.A.', '5 wickets', 'May 21, 2024', 'Prairie View');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'Pakistan', 'Pakistan', '6 wickets', 'May 14, 2024', 'Dublin');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'Pakistan', 'Pakistan', '7 wickets', 'May 12, 2024', 'Dublin');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Zimbabwe', '8 wickets', 'May 12, 2024', 'Mirpur');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Ireland', 'Pakistan', 'Ireland', '5 wickets', 'May 10, 2024', 'Dublin');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Bangladesh', '5 runs', 'May 10, 2024', 'Mirpur');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Bangladesh', '9 runs', 'May 7, 2024', 'Chattogram');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Bangladesh', '6 wickets', 'May 5, 2024', 'Chattogram');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Zimbabwe', 'Bangladesh', '8 wickets', 'May 3, 2024', 'Chattogram');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'Pakistan', '9 runs', 'Apr 27, 2024', 'Lahore');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'New Zealand', '4 runs', 'Apr 25, 2024', 'Lahore');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'New Zealand', '7 wickets', 'Apr 21, 2024', 'Rawalpindi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'Pakistan', '7 wickets', 'Apr 20, 2024', 'Rawalpindi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Pakistan', 'New Zealand', 'no result', '-', 'Apr 18, 2024', 'Rawalpindi');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Ireland', 'Afghanistan', '57 runs', 'Mar 18, 2024', 'Sharjah');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Ireland', 'Afghanistan', '10 runs', 'Mar 17, 2024', 'Sharjah');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Afghanistan', 'Ireland', 'Ireland', '38 runs', 'Mar 15, 2024', 'Sharjah');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Sri Lanka', 'Sri Lanka', '28 runs', 'Mar 9, 2024', 'Sylhet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Sri Lanka', 'Bangladesh', '8 wickets', 'Mar 6, 2024', 'Sylhet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Bangladesh', 'Sri Lanka', 'Sri Lanka', '3 runs', 'Mar 4, 2024', 'Sylhet');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Australia', 'Australia', '27 runs', 'Feb 25, 2024', 'Auckland');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Australia', 'Australia', '72 runs', 'Feb 23, 2024', 'Auckland');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Afghanistan', 'Afghanistan', '3 runs', 'Feb 21, 2024', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Australia', 'Australia', '6 wickets', 'Feb 21, 2024', 'Wellington');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Afghanistan', 'Sri Lanka', '72 runs', 'Feb 19, 2024', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Afghanistan', 'Sri Lanka', '4 runs', 'Feb 17, 2024', 'Dambulla');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'West Indies', 'West Indies', '37 runs', 'Feb 13, 2024', 'Perth');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'West Indies', 'Australia', '34 runs', 'Feb 11, 2024', 'Adelaide');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Australia', 'West Indies', 'Australia', '11 runs', 'Feb 9, 2024', 'Hobart');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'Pakistan', '42 runs', 'Jan 21, 2024', 'Christchurch');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'New Zealand', '7 wickets', 'Jan 19, 2024', 'Christchurch');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Zimbabwe', 'Sri Lanka', '9 wickets', 'Jan 18, 2024', 'Colombo (RPS)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Afghanistan', 'tied', '-', 'Jan 17, 2024', 'Bengaluru');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'New Zealand', '45 runs', 'Jan 17, 2024', 'Dunedin');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Zimbabwe', 'Zimbabwe', '4 wickets', 'Jan 16, 2024', 'Colombo (RPS)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Afghanistan', 'India', '6 wickets', 'Jan 14, 2024', 'Indore');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('Sri Lanka', 'Zimbabwe', 'Sri Lanka', '3 wickets', 'Jan 14, 2024', 'Colombo (RPS)');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'New Zealand', '21 runs', 'Jan 14, 2024', 'Hamilton');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('New Zealand', 'Pakistan', 'New Zealand', '46 runs', 'Jan 12, 2024', 'Auckland');
INSERT INTO T20I (Team1, Team2, Winner, Margin, MatchDate, Ground) VALUES ('India', 'Afghanistan', 'India', '6 wickets', 'Jan 11, 2024', 'Mohali');
